export const ErrorCodes = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  OWNER_NOT_FOUND: 'OWNER_NOT_FOUND',
  DUPLICATE_SKU: 'DUPLICATE_SKU',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  UPLOAD_FAILED: 'UPLOAD_FAILED',
} as const;
